preferred_syntax = :scss
http_path = '/'
css_dir = 'patterns/' #TODO
sass_dir = 'patterns/'
images_dir = 'patterns/'
javascripts_dir = 'patterns/'
relative_assets = true
line_comments = true
# output_style = :compressed
